const startOfToday = () => {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  return today;
};

const formatDate = (date) => {
  const year = date.getFullYear();
  const month = `${date.getMonth() + 1}`.padStart(2, "0");
  const day = `${date.getDate()}`.padStart(2, "0");
  return `${year}-${month}-${day}`;
};

const dateFromOffset = (days) => {
  const date = startOfToday();
  date.setDate(date.getDate() + days);
  return formatDate(date);
};

export const createId = (prefix = "item") =>
  `${prefix}-${Math.random().toString(36).slice(2, 8)}-${Date.now().toString(36)}`;

export function getSeedData() {
  return {
    version: 1,
    savedAt: new Date().toISOString(),
    farm: {
      name: "Sunrise Poultry Estate",
      ownerName: "Mahesh Verma",
      location: "Nashik, Maharashtra",
      contact: "+91 98765 43210",
      notes:
        "30,000 bird operation with four active sheds. Use this dashboard for daily shed control, health planning, stock safety, and profitability tracking.",
    },
    sheds: [
      {
        id: "shed-north-broiler",
        name: "North Broiler 1",
        type: "Broiler",
        capacity: 8000,
        currentBirds: 7800,
        ageDays: 24,
        breed: "Cobb 500",
        batchCode: "B-APR-N1",
        supervisor: "Ajay Patil",
        placementDate: dateFromOffset(-24),
        targetTemp: 28.5,
        targetHumidity: 64,
        notes: "Watch litter moisture near drinker line two and increase evening ventilation if ammonia smell returns.",
      },
      {
        id: "shed-east-broiler",
        name: "East Broiler 2",
        type: "Broiler",
        capacity: 8000,
        currentBirds: 7600,
        ageDays: 21,
        breed: "Ross 308",
        batchCode: "B-APR-E2",
        supervisor: "Kavita More",
        placementDate: dateFromOffset(-21),
        targetTemp: 29,
        targetHumidity: 62,
        notes: "Feed intake is good. Keep checking fan belt tension in the afternoon round.",
      },
      {
        id: "shed-valley-layer",
        name: "Valley Layer 3",
        type: "Layer",
        capacity: 7500,
        currentBirds: 7200,
        ageDays: 122,
        breed: "Hy-Line Brown",
        batchCode: "L-NOV-V3",
        supervisor: "Farhan Shaikh",
        placementDate: dateFromOffset(-122),
        targetTemp: 24,
        targetHumidity: 58,
        notes: "Good shell quality. Keep tray reconciliation tight during evening egg collection.",
      },
      {
        id: "shed-orchard-layer",
        name: "Orchard Layer 4",
        type: "Layer",
        capacity: 7500,
        currentBirds: 7400,
        ageDays: 118,
        breed: "Lohmann Brown",
        batchCode: "L-NOV-O4",
        supervisor: "Neha Jagtap",
        placementDate: dateFromOffset(-118),
        targetTemp: 24.5,
        targetHumidity: 57,
        notes: "Egg numbers are strong. Inspect water pressure if birds crowd around the first nipple line.",
      },
    ],
    vaccinations: [
      {
        id: "vacc-north-nd",
        shedId: "shed-north-broiler",
        disease: "Newcastle + Infectious Bronchitis",
        vaccineName: "Lasota Booster",
        method: "Drinking water",
        dose: "1 vial / 1000 birds",
        batchNo: "VAC-ND-118",
        dueDate: dateFromOffset(1),
        completedDate: "",
        technician: "Dr. R. Singh",
        notes: "Withdraw water for two hours before administration.",
      },
      {
        id: "vacc-east-ibd",
        shedId: "shed-east-broiler",
        disease: "Infectious Bursal Disease",
        vaccineName: "IBD Intermediate Plus",
        method: "Drinking water",
        dose: "1 vial / 1000 birds",
        batchNo: "VAC-IBD-209",
        dueDate: dateFromOffset(2),
        completedDate: "",
        technician: "Dr. R. Singh",
        notes: "Prepare clean drinkers and avoid direct sunlight on diluted vaccine.",
      },
      {
        id: "vacc-east-coryza",
        shedId: "shed-east-broiler",
        disease: "Coryza",
        vaccineName: "Coryza Guard",
        method: "Injection",
        dose: "0.5 ml / bird",
        batchNo: "VAC-COR-031",
        dueDate: dateFromOffset(-1),
        completedDate: "",
        technician: "Kavita More",
        notes: "Overdue entry kept visible intentionally so the owner can act immediately.",
      },
      {
        id: "vacc-valley-pox",
        shedId: "shed-valley-layer",
        disease: "Fowl Pox",
        vaccineName: "Pox Wing Stick",
        method: "Injection",
        dose: "0.01 ml / bird",
        batchNo: "VAC-FPX-407",
        dueDate: dateFromOffset(-3),
        completedDate: dateFromOffset(-3),
        technician: "Farhan Shaikh",
        notes: "Spot-check vaccine takes after seven days.",
      },
      {
        id: "vacc-orchard-nd",
        shedId: "shed-orchard-layer",
        disease: "Newcastle Disease",
        vaccineName: "R2B Booster",
        method: "Eye drop",
        dose: "1 drop / bird",
        batchNo: "VAC-R2B-412",
        dueDate: dateFromOffset(5),
        completedDate: "",
        technician: "Neha Jagtap",
        notes: "Keep a second staff member for tray-side bird handling.",
      },
    ],
    dailyLogs: [
      {
        id: "log-north-yesterday",
        date: dateFromOffset(-1),
        shedId: "shed-north-broiler",
        openingBirds: 7815,
        closingBirds: 7800,
        mortality: 10,
        culls: 5,
        feedKg: 920,
        waterLiters: 4600,
        eggsCollected: 0,
        avgWeight: 1.55,
        temperature: 28.4,
        humidity: 63,
        medicine: "Electrolyte support",
        notes: "Birds stayed active. Slight wet patch near drinker line managed with dry litter.",
      },
      {
        id: "log-east-yesterday",
        date: dateFromOffset(-1),
        shedId: "shed-east-broiler",
        openingBirds: 7612,
        closingBirds: 7600,
        mortality: 9,
        culls: 3,
        feedKg: 905,
        waterLiters: 4510,
        eggsCollected: 0,
        avgWeight: 1.43,
        temperature: 29.1,
        humidity: 61,
        medicine: "Vitamin boost",
        notes: "Mortality is acceptable, but the overdue Coryza vaccine needs action.",
      },
      {
        id: "log-valley-yesterday",
        date: dateFromOffset(-1),
        shedId: "shed-valley-layer",
        openingBirds: 7210,
        closingBirds: 7200,
        mortality: 6,
        culls: 4,
        feedKg: 870,
        waterLiters: 4200,
        eggsCollected: 6650,
        avgWeight: 1.88,
        temperature: 24.7,
        humidity: 58,
        medicine: "Calcium supplement",
        notes: "Excellent lay percentage. Keep evening tray count matching dispatch note.",
      },
      {
        id: "log-orchard-yesterday",
        date: dateFromOffset(-1),
        shedId: "shed-orchard-layer",
        openingBirds: 7412,
        closingBirds: 7400,
        mortality: 7,
        culls: 5,
        feedKg: 885,
        waterLiters: 4280,
        eggsCollected: 6810,
        avgWeight: 1.91,
        temperature: 24.9,
        humidity: 56,
        medicine: "Liver tonic",
        notes: "Production is strong. Watch the first line for uneven water pressure.",
      },
      {
        id: "log-north-two-days",
        date: dateFromOffset(-2),
        shedId: "shed-north-broiler",
        openingBirds: 7828,
        closingBirds: 7815,
        mortality: 8,
        culls: 5,
        feedKg: 910,
        waterLiters: 4520,
        eggsCollected: 0,
        avgWeight: 1.5,
        temperature: 28.7,
        humidity: 64,
        medicine: "None",
        notes: "Even intake across all pans.",
      },
      {
        id: "log-east-two-days",
        date: dateFromOffset(-2),
        shedId: "shed-east-broiler",
        openingBirds: 7624,
        closingBirds: 7612,
        mortality: 7,
        culls: 5,
        feedKg: 892,
        waterLiters: 4445,
        eggsCollected: 0,
        avgWeight: 1.38,
        temperature: 29.3,
        humidity: 62,
        medicine: "None",
        notes: "Afternoon heat load was controlled well after curtain adjustment.",
      },
      {
        id: "log-valley-two-days",
        date: dateFromOffset(-2),
        shedId: "shed-valley-layer",
        openingBirds: 7217,
        closingBirds: 7210,
        mortality: 4,
        culls: 3,
        feedKg: 862,
        waterLiters: 4160,
        eggsCollected: 6585,
        avgWeight: 1.87,
        temperature: 24.4,
        humidity: 57,
        medicine: "None",
        notes: "Minor shell cracking noted in one tray, otherwise stable.",
      },
      {
        id: "log-orchard-two-days",
        date: dateFromOffset(-2),
        shedId: "shed-orchard-layer",
        openingBirds: 7420,
        closingBirds: 7412,
        mortality: 6,
        culls: 2,
        feedKg: 878,
        waterLiters: 4240,
        eggsCollected: 6765,
        avgWeight: 1.9,
        temperature: 24.8,
        humidity: 57,
        medicine: "None",
        notes: "Slight feed wastage near the last line. Adjust pan height during next round.",
      },
    ],
    inventory: [
      {
        id: "stock-broiler-feed",
        name: "Broiler starter feed",
        category: "Feed",
        quantity: 5200,
        unit: "kg",
        reorderLevel: 3000,
        supplier: "Agro Feeds Pvt Ltd",
        expiryDate: dateFromOffset(45),
        unitCost: 32,
      },
      {
        id: "stock-layer-mash",
        name: "Layer mash",
        category: "Feed",
        quantity: 2800,
        unit: "kg",
        reorderLevel: 3500,
        supplier: "Agro Feeds Pvt Ltd",
        expiryDate: dateFromOffset(35),
        unitCost: 30,
      },
      {
        id: "stock-newcastle-vaccine",
        name: "Newcastle vaccine vials",
        category: "Vaccine",
        quantity: 18,
        unit: "vials",
        reorderLevel: 20,
        supplier: "VetCare Distributors",
        expiryDate: dateFromOffset(60),
        unitCost: 450,
      },
      {
        id: "stock-vitamin",
        name: "Vitamin premix",
        category: "Supplement",
        quantity: 65,
        unit: "kg",
        reorderLevel: 25,
        supplier: "NutriBird Solutions",
        expiryDate: dateFromOffset(90),
        unitCost: 185,
      },
      {
        id: "stock-disinfectant",
        name: "Disinfectant concentrate",
        category: "Disinfectant",
        quantity: 48,
        unit: "liters",
        reorderLevel: 15,
        supplier: "BioSecure Agency",
        expiryDate: dateFromOffset(120),
        unitCost: 220,
      },
      {
        id: "stock-diesel",
        name: "Generator diesel",
        category: "Fuel",
        quantity: 210,
        unit: "liters",
        reorderLevel: 100,
        supplier: "Nashik Fuel Point",
        expiryDate: "",
        unitCost: 92,
      },
      {
        id: "stock-antibiotic",
        name: "Support antibiotic kit",
        category: "Medicine",
        quantity: 14,
        unit: "boxes",
        reorderLevel: 20,
        supplier: "VetCare Distributors",
        expiryDate: dateFromOffset(30),
        unitCost: 780,
      },
    ],
    tasks: [
      {
        id: "task-water-shed-1",
        title: "Sanitize water lines before booster dose",
        shedId: "shed-north-broiler",
        category: "Biosecurity",
        dueDate: dateFromOffset(0),
        priority: "High",
        assignedTo: "Ajay Patil",
        completed: false,
        notes: "Flush line fully before vaccine mixing starts tomorrow morning.",
      },
      {
        id: "task-litter-shed-2",
        title: "Top up litter at damp corners",
        shedId: "shed-east-broiler",
        category: "Cleaning",
        dueDate: dateFromOffset(1),
        priority: "Medium",
        assignedTo: "Kavita More",
        completed: false,
        notes: "Prioritize drinker rows and fan-side corners.",
      },
      {
        id: "task-curtain-shed-3",
        title: "Inspect side curtains and patch light leak",
        shedId: "shed-valley-layer",
        category: "Maintenance",
        dueDate: dateFromOffset(-1),
        priority: "Medium",
        assignedTo: "Farhan Shaikh",
        completed: false,
        notes: "Leak near the west flap may disturb evening laying comfort.",
      },
      {
        id: "task-generator",
        title: "Run generator under load for fifteen minutes",
        shedId: "",
        category: "Maintenance",
        dueDate: dateFromOffset(2),
        priority: "High",
        assignedTo: "Rakesh Jadhav",
        completed: false,
        notes: "Confirm auto-switch before the hot-weather week starts.",
      },
      {
        id: "task-egg-trays",
        title: "Reconcile egg tray count with dispatch register",
        shedId: "shed-orchard-layer",
        category: "Inspection",
        dueDate: dateFromOffset(0),
        priority: "Low",
        assignedTo: "Neha Jagtap",
        completed: false,
        notes: "Cross-check damaged trays against breakage notes.",
      },
    ],
    finance: [
      {
        id: "fin-feed-north",
        date: dateFromOffset(-5),
        type: "Expense",
        category: "Feed purchase",
        shedId: "shed-north-broiler",
        counterparty: "Agro Feeds Pvt Ltd",
        amount: 45000,
        notes: "Two-day feed stock refill for broiler lot.",
      },
      {
        id: "fin-feed-east",
        date: dateFromOffset(-4),
        type: "Expense",
        category: "Feed purchase",
        shedId: "shed-east-broiler",
        counterparty: "Agro Feeds Pvt Ltd",
        amount: 43000,
        notes: "Ross 308 feed line top-up.",
      },
      {
        id: "fin-vaccine",
        date: dateFromOffset(-3),
        type: "Expense",
        category: "Vaccine purchase",
        shedId: "",
        counterparty: "VetCare Distributors",
        amount: 12000,
        notes: "Booster stock for broiler and layer schedule.",
      },
      {
        id: "fin-electricity",
        date: dateFromOffset(-2),
        type: "Expense",
        category: "Electricity",
        shedId: "",
        counterparty: "MSEDCL",
        amount: 16000,
        notes: "Monthly utility bill.",
      },
      {
        id: "fin-labour",
        date: dateFromOffset(-1),
        type: "Expense",
        category: "Labour",
        shedId: "",
        counterparty: "Farm payroll",
        amount: 22000,
        notes: "Weekly wage settlement.",
      },
      {
        id: "fin-egg-valley",
        date: dateFromOffset(-1),
        type: "Income",
        category: "Egg sale",
        shedId: "shed-valley-layer",
        counterparty: "FreshNest Retail",
        amount: 68000,
        notes: "Morning dispatch.",
      },
      {
        id: "fin-egg-orchard",
        date: dateFromOffset(-1),
        type: "Income",
        category: "Egg sale",
        shedId: "shed-orchard-layer",
        counterparty: "FreshNest Retail",
        amount: 70500,
        notes: "Evening dispatch.",
      },
      {
        id: "fin-manure",
        date: dateFromOffset(-2),
        type: "Income",
        category: "Manure sale",
        shedId: "",
        counterparty: "Green Soil Traders",
        amount: 9000,
        notes: "Farm side pickup.",
      },
    ],
  };
}
