version: "3.9"

services:
  portfolio-db:
    image: mysql:8.4
    container_name: portfolio-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: portfolio_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  portfolio-app:
    build: .
    container_name: portfolio-app
    restart: unless-stopped
    depends_on:
      - portfolio-db
    environment:
      PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://portfolio-db:3306/portfolio_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"

volumes:
  mysql-data:
